apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis
  labels:
    app: sentiment-analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-analysis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sentiment-analysis
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: sentiment-analysis
        image: ${DOCKER_USERNAME}/ml-devops-sentiment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: PORT
          value: "5000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  labels:
    app: sentiment-analysis
spec:
  selector:
    app: sentiment-analysis
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-analysis-monitor
  labels:
    app: sentiment-analysis
spec:
  selector:
    matchLabels:
      app: sentiment-analysis
  endpoints:
  - port: http
    interval: 15s
    path: /metrics